#!/usr/bin/env bash
set -u

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MA_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
LOG_DIR="$MA_DIR/logs/runs"
MSG_DIR="$MA_DIR/logs/messages"
mkdir -p "$LOG_DIR" "$MSG_DIR"

INPUT_FILE=""
OUTPUT_FILE=""
GOAL=""
TASK_ID="hermes_$(date +%Y%m%d_%H%M%S)"
HERMES_TIMEOUT_SECONDS="${HERMES_TIMEOUT_SECONDS:-30}"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --input)
      INPUT_FILE="${2:-}"
      shift 2
      ;;
    --output)
      OUTPUT_FILE="${2:-}"
      shift 2
      ;;
    --goal)
      GOAL="${2:-}"
      shift 2
      ;;
    --task-id)
      TASK_ID="${2:-}"
      shift 2
      ;;
    *)
      printf 'unknown argument: %s\n' "$1" >&2
      exit 64
      ;;
  esac
done

if [[ -z "$INPUT_FILE" || -z "$OUTPUT_FILE" ]]; then
  printf 'usage: call_hermes.sh --input PLAN --output REVIEW [--goal GOAL]\n' >&2
  exit 64
fi

RUN_LOG="$LOG_DIR/${TASK_ID}_hermes.log"
PROMPT_FILE="$MSG_DIR/${TASK_ID}_hermes_prompt.md"
TMP_OUTPUT="$MSG_DIR/${TASK_ID}_hermes_raw.md"
HELP_FILE="$MSG_DIR/${TASK_ID}_hermes_help.txt"

{
  printf '# Hermes Review Request\n\n'
  printf '## User Goal\n\n%s\n\n' "$GOAL"
  printf '## Analyst Plan\n\n'
  cat "$INPUT_FILE"
  printf '\n\n## Required Output\n\n'
  printf -- '- 总体评价:\n- 方案优点:\n- 潜在问题:\n- 遗漏风险:\n- 优化建议:\n- 最终建议: approve | revise | reject\n'
} > "$PROMPT_FILE"

printf 'Hermes prompt: %s\n' "$PROMPT_FILE" >> "$RUN_LOG"

write_fallback() {
  local reason="$1"
  cat > "$OUTPUT_FILE" <<EOF
## Hermes Review

- source: fallback
- reason: $reason
- 总体评价: fallback review generated by the local adapter.
- 方案优点: Analyst plan has a bounded file scope and explicit verification section.
- 潜在问题: External Hermes reasoning did not complete successfully, so this is not a full second opinion.
- 遗漏风险: Architecture, security, or over-design risks may still require human review.
- 优化建议: Analyst should keep scope tight, preserve Guard checks, and run smoke tests before execution.
- 最终建议: revise
decision: revise
EOF
}

if command -v hermes >/dev/null 2>&1; then
  printf 'hermes: found at %s\n' "$(command -v hermes)" >> "$RUN_LOG"
  timeout 20 hermes chat --help > "$HELP_FILE" 2>> "$RUN_LOG" || true
  if ! grep -Eq -- '-q QUERY|--query QUERY' "$HELP_FILE"; then
    printf 'hermes chat help did not expose -q/--query\n' >> "$RUN_LOG"
    write_fallback "hermes chat does not expose non-interactive query mode"
    printf 'Hermes review written: %s\n' "$OUTPUT_FILE" >> "$RUN_LOG"
    printf '%s\n' "$OUTPUT_FILE"
    exit 0
  fi
  PROMPT_TEXT="$(cat "$PROMPT_FILE")"
  timeout "$HERMES_TIMEOUT_SECONDS" hermes chat -Q --max-turns 1 -q "$PROMPT_TEXT" > "$TMP_OUTPUT" 2>> "$RUN_LOG"
  STATUS=$?
  if [[ "$STATUS" -eq 0 && -s "$TMP_OUTPUT" ]]; then
    if grep -Eqi '最终建议:[[:space:]]*(approve|revise|reject)|decision:[[:space:]]*(approve|revise|reject)|final recommendation:[[:space:]]*(approve|revise|reject)' "$TMP_OUTPUT"; then
      cp "$TMP_OUTPUT" "$OUTPUT_FILE"
      if ! grep -Eqi '最终建议|final recommendation' "$OUTPUT_FILE"; then
        cat >> "$OUTPUT_FILE" <<'EOF'

## Hermes Adapter Note

- 总体评价: Hermes returned partial review output.
- 方案优点: See Hermes output above.
- 潜在问题: Final recommendation was missing.
- 遗漏风险: Review may be incomplete.
- 优化建议: Analyst should revise the plan before execution.
- 最终建议: revise
decision: revise
EOF
      fi
    else
      printf 'hermes output did not match review format, writing fallback review\n' >> "$RUN_LOG"
      write_fallback "hermes returned output without explicit approve/revise/reject"
    fi
  else
    printf 'hermes call failed or produced empty output, status=%s\n' "$STATUS" >> "$RUN_LOG"
    write_fallback "hermes non-interactive call failed or timed out with status $STATUS"
  fi
else
  printf 'hermes: missing, writing fallback review\n' >> "$RUN_LOG"
  write_fallback "hermes command not found"
fi

printf 'Hermes review written: %s\n' "$OUTPUT_FILE" >> "$RUN_LOG"
printf '%s\n' "$OUTPUT_FILE"
